### ISSUE TITLE
🐞 全部报错指令异常

### ISSUE THREAD

**Issue by LingyiChen-AI** [ConnectAI-E/Feishu-Midjourney#11]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

<img width="627" alt="image" src="https://user-images.githubusercontent.com/44161003/234770086-af508abf-6a7c-4df5-adc1-c346a34dbdb1.png">

一个用户，全部指令异常

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by Leizhenpeng** [comment]
discord 中机器人的消息解读开关没有打开
![image](https://user-images.githubusercontent.com/50035229/235292847-537cf823-15aa-401f-8e47-45836dc3033b.png)

**Comment by LingyiChen-AI** [comment]
开启也是一样的错误提示 @Leizhenpeng
