### ISSUE TITLE
求加群 一同开发

### ISSUE THREAD

**Issue by gumplus** [ConnectAI-E/Feishu-Midjourney#2]

**Comment by Can-Chen** [comment]
1375883312@qq.com邮箱发送您的微信号 我拉您

**Comment by Can-Chen** [comment]
1375883312@qq.com邮箱发送您的微信号 我拉您

**Comment by gumplus** [comment]
微信号：Cryptosun


| |
Gump cheng
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年04月18日 23:36 |
| 收件人 | ***@***.***> |
| 抄送人 | Gump ***@***.***> ,
***@***.***> |
| 主题 | Re: [ConnectAI-E/Feishu-Midjourney-Proxy] 求加群 一同开发 (Issue #2) |

***@***.***邮箱发送您的微信号 我拉您
