### ISSUE TITLE
🚰 部署问题反馈

### ISSUE THREAD

**Issue by Eventidus** [ConnectAI-E/Feishu-Midjourney#22]
![image](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/49816387/c9ea548d-d59d-4cf2-81c3-5a80e066eddd)

token是正常的

**Comment by thesong513** [comment]
我这里修改了 docker-compose.yaml里面的环境变量，就ok了

**Comment by Eventidus** [comment]
您好 可以请教一下具体是怎么修改的吗？

**Comment by thesong513** [comment]
![image](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/30562225/5a7f3078-54e3-45fd-a364-8cb699939fc0)
目录下面有个 docker-compose.yaml文件，把里面的参数都改正自己的，按照那个部署文档里面的内容

**Comment by Eventidus** [comment]
好的 谢谢您 原来如此啊

**Comment by Iambihua** [comment]
我执行docker-compose build 以及 docker-compose build命令后就卡在 Attaching to feishu-midjourney_midjourney_1, feishu-midjourney_lark_1 这一步了，你有解决办法吗？lark以及midjourney目录下config.yaml文件是否还需要额外配置?
![image](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/49816387/29dffa09-533a-44ab-a920-8dafae1857db)

**Comment by thesong513** [comment]
这是代表已经启动了 你后面加个 -d 后台运行

**Comment by Eventidus** [comment]
是这样吗，但是飞书后台添加订阅地址时显示请求地址超时
![image](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/49816387/a711dcfe-00cb-437f-9a09-3d93fb8bc747)
