### ISSUE TITLE
部署问题反馈

### ISSUE THREAD

**Issue by knowlimit** [ConnectAI-E/Feishu-Midjourney#28]
# 错误报告 🐞
配置完成都确保正常后，执行指令后出现指令异常错误
![微信图片_20230528232508](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/106434682/3c065a00-bfdc-4bc2-a4dd-a16489a76ab2)
![微信图片_20230528232536](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/106434682/26251508-c5c5-4be4-bf93-588b823f49b4)

**如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题**。

## 错误描述 🤔

请详细地描述您遇到的问题，包括出现问题的环境和步骤，以及您已经尝试过的解决方法。

另外，如果您在解决问题时已经查看过其他 GitHub Issue，请务必在文本中说明并引用相关信息。

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by knowlimit** [comment]
ubuntu 20

**Comment by knowlimit** [comment]
我直接运行的 go run main.go

**Comment by knowlimit** [comment]
查看了一下，我的discord机器人没有开始绘图。就是操作句柄没有找到

**Comment by knowlimit** [comment]
解决了，要启动两个应用，分别在lark,和mj 目录，两个端口16007和16008

**Comment by knowlimit** [comment]
2023/05/28 17:11:00 [Error] [handle event,path:/webhook/event,error:event type: im.message.message_read_v1, not found handler]，我在discord的机器人也生成了图片，但是还是报错，异常

**Comment by knowlimit** [comment]
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :16008
2023/05/28 17:10:57 [Error] [handle cardAcion,path:/webhook/card, err: the result of signature verification failed]
[GIN] 2023/05/28 - 17:10:57 | 500 |     517.064µs | 107.172.142.132 | POST     "/webhook/card"
2023/05/28 17:11:00 [Error] [handle event,path:/webhook/event,error:event type: im.message.message_read_v1, not found handler]
[GIN] 2023/05/28 - 17:11:00 | 200 |     219.913µs |   123.58.10.238 | POST     "/webhook/event"
检查指令中 85c69fbaa9b6 0
[GIN] 2023/05/28 - 17:11:14 | 200 |     539.779µs |   123.58.10.239 | POST     "/webhook/event"
检查指令中 85c69fbaa9b6 1
2023/05/28 17:11:34 [Error] [handle cardAcion,path:/webhook/card, err: the result of signature verification failed]
[GIN] 2023/05/28 - 17:11:34 | 500 |     430.252µs | 107.172.142.132 | POST     "/webhook/card"
指令异常 85c69fbaa9b6 2
[GIN] 2023/05/28 - 17:11:42 | 200 | 47.014924019s |   123.58.10.239 | POST     "/webhook/event"
2023/05/28 17:11:46 [Error] [handle event,path:/webhook/event,error:event type: im.message.message_read_v1, not found handler]
[GIN] 2023/05/28 - 17:11:46 | 200 |     563.882µs |   123.58.10.239 | POST     "/webhook/event"

**Comment by knowlimit** [comment]
**err: the result of signature verification failed**

**Comment by knowlimit** [comment]
[最后两个程序打开][http://aigctob.com.cn/err1.png](url)

**Comment by knowlimit** [comment]
`Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :16008
2023/05/29 01:11:26 [Error] [handle cardAcion,path:/webhook/card, err: the result of signature verification failed]
[GIN] 2023/05/29 - 01:11:26 | 500 |     727.371µs | 107.172.142.132 | POST     "/webhook/card"
检查指令中 abfb6b1540ce 0
[GIN] 2023/05/29 - 01:11:44 | 200 |     452.904µs |   123.58.10.239 | POST     "/webhook/event"
2023/05/29 01:11:49 [Error] [handle event,path:/webhook/event,error:event type: im.message.message_read_v1, not found handler]
[GIN] 2023/05/29 - 01:11:49 | 200 |     476.341µs |   123.58.10.239 | POST     "/webhook/event"
检查指令中 abfb6b1540ce 1
2023/05/29 01:12:04 [Error] [handle cardAcion,path:/webhook/card, err: the result of signature verification failed]
[GIN] 2023/05/29 - 01:12:04 | 500 |     451.881µs | 107.172.142.132 | POST     "/webhook/card"
指令异常 abfb6b1540ce 2
[GIN] 2023/05/29 - 01:12:12 | 200 | 46.901965796s |   123.58.10.239 | POST     "/webhook/event"
2023/05/29 01:12:15 [Error] [handle event,path:/webhook/event,error:event type: im.message.message_read_v1, not found handler]
[GIN] 2023/05/29 - 01:12:15 | 200 |     473.777µs |   123.58.10.238 | POST     "/webhook/event"
2023/05/29 01:16:33 [Info] [AuthByChallenge Success]
[GIN] 2023/05/29 - 01:16:33 | 200 |       668.2µs |   123.58.10.239 | POST     "/webhook/card"
2023/05/29 01:16:35 [Info] [AuthByChallenge Success]
[GIN] 2023/05/29 - 01:16:35 | 200 |     291.772µs |   123.58.10.239 | POST     "/webhook/card"`

**Comment by Leizhenpeng** [comment]
<img width="923" alt="image" src="https://github.com/ConnectAI-E/Feishu-Midjourney/assets/50035229/7702a4e3-4ae6-4ec3-a0ec-ade7150c6820">

看下上面的权限是不是没有打开
