### ISSUE TITLE
🚰 部署问题反馈

### ISSUE THREAD

**Issue by knowlimit** [ConnectAI-E/Feishu-Midjourney#29]
# 问题交流 💬

欢迎在此提交您遇到的问题，我们会尽快回复您并提供帮助。

## 问题描述 🤔
配置了两个机器人，包括飞书和discord。能够正常的生成图片。但是飞书机器人总是指令异常。查看交互日志发现错误：

`Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :16008
2023/05/29 08:22:49 [Error] [handle cardAcion,path:/webhook/card, err: the result of signature verification failed]
[GIN] 2023/05/29 - 08:22:49 | 500 |     273.306µs | 107.172.142.132 | POST     "/webhook/card"
检查指令中 9c305f81efc7 0
[GIN] 2023/05/29 - 08:23:07 | 200 |  244.381738ms |   123.58.10.238 | POST     "/webhook/event"
2023/05/29 08:23:11 [Error] [handle event,path:/webhook/event,error:event type: im.message.message_read_v1, not found handler]
[GIN] 2023/05/29 - 08:23:11 | 200 |  216.075268ms |   123.58.10.238 | POST     "/webhook/event"
检查指令中 9c305f81efc7 1
2023/05/29 08:23:32 [Error] [handle cardAcion,path:/webhook/card, err: the result of signature verification failed]
[GIN] 2023/05/29 - 08:23:32 | 500 |     579.995µs | 107.172.142.132 | POST     "/webhook/card"
指令异常 9c305f81efc7 2
[GIN] 2023/05/29 - 08:23:35 | 200 | 47.384989476s |   123.58.10.239 | POST     "/webhook/event"
2023/05/29 08:23:39 [Error] [handle event,path:/webhook/event,error:event type: im.message.message_read_v1, not found handler]
[GIN] 2023/05/29 - 08:23:39 | 200 |  238.670248ms |   123.58.10.238 | POST     "/webhook/event"`
请详细描述您遇到的问题，包括出现问题的环境和步骤，以及您已经尝试过的解决方法。

如果您在解决问题时已经查看过其他 GitHub Issue，请务必在文本中说明并引用相关信息。

## 附加信息 📝
![image](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/106434682/3a43e7a4-7ad6-4a64-80eb-710bb5eedbb6)

为了更好地了解您遇到的问题，我们需要您提供以下信息：

- 输出日志，包括错误信息和堆栈跟踪。
- 相关的代码片段或文件。
- 操作系统、golang 版本等环境信息。

感谢您的反馈和支持！🙏

**Comment by Leizhenpeng** [comment]
message_read_v1 只是说明没有处理消息已读的飞书事件回调
