### ISSUE TITLE
生成图片discord报如下错误

### ISSUE THREAD

**Issue by MIMI180306** [ConnectAI-E/Feishu-Midjourney#35]
{"code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATION_COMMAND_INVALID_VERSION", "message": "\u8be5\u6743\u9650\u5df2\u8fc7\u65f6\uff0c\u8bf7\u7a0d\u5019\u51e0\u5206\u949f\u518d\u8bd5"}]}}, "message": "Invalid Form Body"} <nil> 400 Bad Request https://discord.com/api/v9/interactions

**Comment by MIMI180306** [comment]
忘更新version了

**Comment by wslyyy** [comment]
请问如何解决？

**Comment by MIMI180306** [comment]
> 请问如何解决？

换一下发送报文里的version，代码里已经更新了

**Comment by wslyyy** [comment]
> > 请问如何解决？
> 
> 换一下发送报文里的version，代码里已经更新了

version具体换成什么，在哪里能找到

**Comment by MIMI180306** [comment]
> > > 请问如何解决？
> > 
> > 
> > 换一下发送报文里的version，代码里已经更新了
> 
> version具体换成什么，在哪里能找到

midjourney/services/discord.go 这个里面 
![image](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/45851793/297301c4-d6e9-41ea-8383-4d649ec67fb2)
