### ISSUE TITLE
discord api 返回信息错误 50035 显示：表单主体无效

### ISSUE THREAD

**Issue by wmily1** [ConnectAI-E/Feishu-Midjourney#42]
response: {"message": "表单主体无效", "code": 50035, "errors": {"data": {"_errors": [{"code": "interaction_application_command_invalid_version", "message": "该权限已过时，请稍候几分钟再试"}]}}} <nil> 400 bad request https://discord.com/api/v9/interactions

飞书返回：

🤖️ ：发送的指令存在异常，请检查后重试

**Comment by jiangshuichu** [comment]
我也出现这个错误，之前可以成功的请求，昨天全都报这个错误。

**Comment by Eventidus** [comment]
+1

**Comment by jiangshuichu** [comment]
GenerateImage 函数里的version字段好像是个变动的值，从mj的页面里把接口中的version值copy出来替换一下就行了

**Comment by wmily1** [comment]
> GenerateImage 函数里的version字段好像是个变动的值，从mj的页面里把接口中的version值copy出来替换一下就行了

替换过了，还是报这个错误

**Comment by jiangshuichu** [comment]
> > GenerateImage 函数里的version字段好像是个变动的值，从mj的页面里把接口中的version值copy出来替换一下就行了
> 
> 替换过了，还是报这个错误

额，我替换完就正常了

**Comment by wmily1** [comment]
> > > GenerateImage 函数里的version字段好像是个变动的值，从mj的页面里把接口中的version值copy出来替换一下就行了
> > 
> > 
> > 替换过了，还是报这个错误
> 
> 额，我替换完就正常了

我是用的是宝塔，go项目的替换完了之后需不需要清缓存什么的？

![image](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/43977018/56667581-2882-4457-881e-63ec587b0e8e)


我替换了这两个值。

![image](https://github.com/ConnectAI-E/Feishu-Midjourney/assets/43977018/f5c9fb2e-a5f0-4fe7-9066-a369bfa48f65)

**Comment by wmily1** [comment]
我该

> > > > GenerateImage 函数里的version字段好像是个变动的值，从mj的页面里把接口中的version值copy出来替换一下就行了
> > > 
> > > 
> > > 替换过了，还是报这个错误
> > 
> > 
> > 额，我替换完就正常了


确实好了，修改了version id 和DISCORD_USER_TOKEN，将宝塔里面的启动方式改成go run main.go，好了，之前是修改了，启动方式还是go build的文件，才没有生效。
