### ISSUE TITLE
📝 文档改善 优化readm界面

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/Feishu-Midjourney#5]
# 文档改善建议 📝

欢迎在此分享您对文档的改善建议，我们期待听到您的想法和建议。

## 您的建议是什么？ 🤔

突出点
- 震撼的使用效果
- 清洗的上手指引
- 整体美观

**Comment by Tourt-Y** [comment]
大佬能不能整个部署文档

**Comment by licstar** [comment]
用户们合写的文档，可以先用一下
https://docs.qq.com/doc/DUFdLQlBVenB5d1FI?u=7d77bd81c370469ea87e8769a9a176ab
