### ISSUE TITLE
怎么获取/info的回调内容？

### ISSUE THREAD

**Issue by liuyan345** [ConnectAI-E/Feishu-Midjourney#9]
我想获取我账号的剩余使用情况
我在接口/v1/trigger/midjourney-bot 写了个 info方法，可以发起查询操作
但是在handlers/discord.go中，我该怎么写才能获取到info的查询结果？
是需要在设置自己的机器人权限那里勾选响应的权限吗？ 
我勾选了TEXT PERMISSIONS-> send message/ read Mssage History / use slash commands

**Comment by Leizhenpeng** [comment]
![image](https://user-images.githubusercontent.com/50035229/235292885-0e9bf9c5-7417-475c-bb6c-b8206e75adda.png)
